# Generated by Django 3.1 on 2020-10-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordmanager', '0002_create_default_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(help_text='longitude')),
                ('y', models.FloatField(help_text='latitude')),
            ],
            options={
                'verbose_name': 'coordinate',
                'verbose_name_plural': 'coordinates',
            },
        ),
    ]
