# Generated by Django 3.1 on 2020-10-05 04:45

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordmanager', '0003_coordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(help_text='longitude')),
                ('y', models.FloatField(help_text='latitude')),
                ('operation', models.CharField(choices=[('N', 'nearest point'), ('F', 'furthest point')], help_text='operation type', max_length=1)),
                ('num_point', models.PositiveIntegerField(help_text='number of points to be returned')),
                ('request_datetime', models.DateTimeField(auto_now_add=True, help_text='request date time')),
                ('evaluation_datetime', models.DateTimeField(default=None, editable=False, help_text='result evaluation date time', null=True)),
                ('results', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2), default=None, editable=False, null=True, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'result',
                'verbose_name_plural': 'results',
                'ordering': ['-request_datetime'],
            },
        ),
    ]
