version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: coordmanager_local_django
    container_name: coordmanager_django
    depends_on:
      - postgres
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    volumes:
      - .:/app:z
      - ./"${CSV_IMPORT_DIR}":/"${CSV_IMPORT_DIR}":z
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: coordmanager_production_postgres
    container_name: coordmanager_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: coordmanager_local_docs
    container_name: coordmanager_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
    ports:
      - "7000:7000"

  redis:
    image: redis:5.0
    container_name: coordmanager_redis

  celeryworker:
    <<: *django
    image: coordmanager_local_celeryworker
    container_name: coordmanager_celeryworker
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: coordmanager_local_celerybeat
    container_name: coordmanager_celerybeat
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: coordmanager_local_flower
    container_name: coordmanager_flower
    ports:
      - "5555:5555"
    command: /start-flower

  jupyter:
    <<: *django
    image: coordmanager_local_jupyter
    container_name: coordmanager_jupyter
    ports:
      - "8888:8888"
    command: /start-jupyter
